server:
  port: 8081

jwt:
  secret: my-super-secret-key-that-is-long-enough-to-be-secure

spring:
  application:
    name: PRODUCT-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/shopezMicroservice
    username: root
    password: Shubham@123k

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
