server:
  port: 8083

spring:
  application:
    name: PAYMENT-SERVICE

  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    url: jdbc:mysql://localhost:3306/shopezMicroservice
    username: root
    password: Shubham@123k

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect