server:
  port: 8081

jwt:
  secret: my-super-secret-key-that-is-long-enough-to-be-secure
  expiration: 3600000 # 1 hour

spring:
  application:
    name: AUTH-SERVICE
  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    url: jdbc:mysql://localhost:3306/shopezMicroservice
    username: root
    password: Shubham@123k

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
